name: Build and Package LaTeX DTX and INS Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: texlive/texlive:latest

    steps:
      - name: Install requirements
        run: |
          apt-get update
          apt-get install -y zip
    
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run LaTeX INS file
        run: latex temporal-logic.ins
      
      - name: Build PDF from DTX
        run: | 
          latexmk -pdf temporal-logic.dtx
          mv temporal-logic.pdf temporal-logic-doc.pdf

      - name: Create ZIP archive for CTAN
        run: |
          mkdir temporal-logic
          cp temporal-logic.dtx temporal-logic/
          cp temporal-logic.ins temporal-logic/
          cp temporal-logic-doc.pdf temporal-logic/
          cp README.md temporal-logic/
          zip -r temporal-logic.zip temporal-logic

      - name: Upload ZIP file
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            temporal-logic.zip
            temporal-logic.sty
